name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: |
        python -m pip install --upgrade pip xpip-build xpip-upload
        python -m pip --version
        python -m pip list
    - name: Build and Test
      run: |
        make build install test
    - name: Upload to PyPI
      run: |
        xpip-upload --token ${{ secrets.PYPI_TOKEN }} dist/*

  pypi-index:
    needs: pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          PROJECT=$(python3 -c "from xkits_command.attribute import __project__; print(__project__)")
          VERSION=$(python3 -c "from xkits_command.attribute import __version__; print(__version__)")
          while true; do python -m pip install $PROJECT==$VERSION && break || sleep 5; done
